language: generic 

sudo: requierd 
service:
  - docker 

before_install:
  - docker build -t arikuz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arikuz/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-182549974023"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"