language: generic 

sudo: requierd 
service:
  - docker 

before_install:
  - docker build -t arikuz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arikuz/docker-react npm run test